DROP TABLE IF EXISTS products;
CREATE TABLE products (
id SERIAL,
name VARCHAR(64) NOT NULL,
description VARCHAR(64) NOT NULL,
category VARCHAR(64) NOT NULL,
brand VARCHAR (64),
tags ARRAY NOT NULL,
created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);